### ISSUE TITLE
Client.contract won't throw/return an error when the call should definitely revert

### ISSUE THREAD

**Issue by 0xpolarzero** [evmts/tevm-monorepo#990] opened 2024-03-03 19:18 UTC
## Description

I'm not sure what happens here, but I might as well drop it with a reproductible example.

Feel free to keep it aside, I'll add any other instances of such case that can provide more context (i.e. with different enough parameters).

Basically a call that should obviously revert (making calls to a contract that doesn't even exist) does not, and returns a "normal" result.

```javascript
{
  rawData: '0x',
  executionGasUsed: 3724n,
  selfdestruct: Set(0) {},
  gas: 16773491n,
  logs: [],
  createdAddresses: Set(0) {},
  data: undefined
}
```

[See the runnable example here](https://github.com/0xpolarzero/tevm-minimal-repro/blob/main/bug-no-revert/index.ts).

**Comment by roninjin10** [comment] 2024-03-03 19:53
Root cause here is the `ForkStateManager` falsely thinking that contract code exists on certain networks (such as optimism) but not others (such as polygon). You can see this by calling `getAccount` on these networks as the normal state manager will throw while ForkStateManager will return what it thinks is a contract.

The code that has the bug is here https://github.com/evmts/tevm-monorepo/blob/main/packages/state/src/ForkStateManager.ts#L301

**Comment by roninjin10** [comment] 2024-05-04 04:23
This was a bug in geth (too lazy to link geth issue at this time but I found it via looking at changelog).  I reported it to json-rpc providers with a minimal repro in march. It should be fixed by now.

**Closed by roninjin10** 2024-05-04 04:23 UTC
Labels: good first issue
